### ISSUE TITLE
Ignore the Tab Manager Tab while collapsing?

### ISSUE THREAD

**Issue by JRavi2** [daemon1024/TabuRei#20]
Currently, when the current set of tabs are collapsed, the tab manager tab is also saved.
I think that tab could be ignored while collapsing?

**Comment by daemon1024** [comment]
Nice Catch. Thanks for pointing this out 😃 We are currently filtering out about pages, maybe we could filter out moz-extension pages too 🤔

**Comment by JRavi2** [comment]
Yup! That'll do it. I'll make a PR for it in a few days

**Comment by akshgpt7** [comment]
@JRavi2 I think it'll make more sense to just filter out the `TuabuRei` tab instead of all the moz-extensions (someone might have another extension opened for something useful). So just check for the `TabuRei` tab and filter that out while collapsing.

**Comment by JRavi2** [comment]
Yeah, you're right, that would also decrease the dependency on the type of browser!
