### ISSUE TITLE
Fix positioning of buttons in popup

### ISSUE THREAD

**Issue by daemon1024** [daemon1024/TabuRei#29]
Currently when there are too many tabs in the current window, we need to scroll down too much to reach out the button group. This is kinda anti UX.

Proposed solution could be provilding the button above the list or fix the button group position so that list scrolls below it.

**Comment by Serjeel-Ranjan-911** [comment]
By "button group" do you mean Collapse and Tab Manager button??

**Comment by akshgpt7** [comment]
@Serjeel-Ranjan-911 Yes, those buttons in the popup.

**Comment by Serjeel-Ranjan-911** [comment]
![image](https://user-images.githubusercontent.com/74287984/110066336-348b2500-7d97-11eb-8c0f-f0729cfef071.png)

is something like this expected?

**Comment by daemon1024** [comment]
@Serjeel-Ranjan-911 LGTM. Just a note, Do the buttons scroll away? I just want the buttons to be accessible all the time despite any scrolling.

It seems like you are already working on this issue. Should I assign it to you? Thank You ☺️

**Comment by Serjeel-Ranjan-911** [comment]
Yes you can assign me this issue.

**Comment by Serjeel-Ranjan-911** [comment]
#31 Please check.
