### ISSUE TITLE
Refactor deprecated keyCode check

### ISSUE THREAD

**Issue by akshgpt7** [daemon1024/TabuRei#37]
The `keyCode` parameter is deprecated. This is being used in the `js/tab-manager.js` file inside the `keyup` event to confirm the change of group name.

This might be a bit tricky, since there are different implementations out there for several browsers. We might have to add multiple checks, or choose the best one out of them.

**Comment by aaryanporwal** [comment]
We can just use [KeyboardEvent.code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) instead
